<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3153" started-at="2019-04-22T16:21:51Z" finished-at="2019-04-22T16:21:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3153" started-at="2019-04-22T16:21:51Z" finished-at="2019-04-22T16:21:55Z">
      <class name="Test_Cases.ResourceUsersTests">
        <test-method status="PASS" signature="resource_Users_Get()[pri:0, instance:Test_Cases.ResourceUsersTests@1aeed2f]" name="resource_Users_Get" duration-ms="2538" started-at="2019-04-22T16:21:51Z" finished-at="2019-04-22T16:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resource_Users_Get -->
        <test-method status="FAIL" signature="resource_Users_Post()[pri:0, instance:Test_Cases.ResourceUsersTests@1aeed2f]" name="resource_Users_Post" duration-ms="371" started-at="2019-04-22T16:21:54Z" finished-at="2019-04-22T16:21:54Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<500> but was:<201>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<500> but was:<201>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at Test_Cases.ResourceUsersTests.resource_Users_Post(ResourceUsersTests.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resource_Users_Post -->
        <test-method status="PASS" signature="resource_Users_Put()[pri:0, instance:Test_Cases.ResourceUsersTests@1aeed2f]" name="resource_Users_Put" duration-ms="138" started-at="2019-04-22T16:21:54Z" finished-at="2019-04-22T16:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resource_Users_Put -->
      </class> <!-- Test_Cases.ResourceUsersTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
